/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as RecipientsIdRouteImport } from './routes/recipients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientsIdRoute = RecipientsIdRouteImport.update({
  id: '/recipients/$id',
  path: '/recipients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/templates': typeof TemplatesRoute
  '/upload': typeof UploadRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/recipients/$id': typeof RecipientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/templates': typeof TemplatesRoute
  '/upload': typeof UploadRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/recipients/$id': typeof RecipientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/templates': typeof TemplatesRoute
  '/upload': typeof UploadRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/editor/$id': typeof EditorIdRoute
  '/recipients/$id': typeof RecipientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/templates'
    | '/upload'
    | '/campaigns/$id'
    | '/editor/$id'
    | '/recipients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/templates'
    | '/upload'
    | '/campaigns/$id'
    | '/editor/$id'
    | '/recipients/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/templates'
    | '/upload'
    | '/campaigns/$id'
    | '/editor/$id'
    | '/recipients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  TemplatesRoute: typeof TemplatesRoute
  UploadRoute: typeof UploadRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  EditorIdRoute: typeof EditorIdRoute
  RecipientsIdRoute: typeof RecipientsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipients/$id': {
      id: '/recipients/$id'
      path: '/recipients/$id'
      fullPath: '/recipients/$id'
      preLoaderRoute: typeof RecipientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  TemplatesRoute: TemplatesRoute,
  UploadRoute: UploadRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  EditorIdRoute: EditorIdRoute,
  RecipientsIdRoute: RecipientsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
